name: Generate Datas

on:
  schedule: # Executar a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs para atualizar os dados
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
      
      - name: Configurar o Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Instalar as dependências
        run: npm install

      - name: Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: psiotavio
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Publicar páginas do GitHub
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
